/* Generated by tradukisto - do not edit manually */

import z from "zod/v4";

export const frontpagePostsListSchema = z.object({
  _id: z.string(),
  slug: z.string(),
  title: z.string(),
  baseScore: z.number(),
  voteCount: z.number(),
  commentCount: z.number(),
  postedAt: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val)))),
  curatedDate: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
    .nullable(),
  isEvent: z.boolean(),
  groupId: z.string().nullable(),
  sticky: z.boolean(),
  eventImageId: z.string().nullable(),
  socialPreview: z.json().nullable(),
  socialPreviewImageAutoUrl: z.string().nullable(),
  readTimeMinutesOverride: z.number().nullable(),
  wordCount: z.number().nullable(),
  htmlHighlight: z.string().nullable(),
  user: z.object({
    _id: z.string().nullable(),
    slug: z.string().nullable(),
    displayName: z.string().nullable(),
    createdAt: z
      .union([z.string(), z.date()])
      .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
      .nullable(),
    profileImageId: z.string().nullable(),
    karma: z.number().nullable(),
    jobTitle: z.string().nullable(),
    organization: z.string().nullable(),
    postCount: z.number().nullable(),
    commentCount: z.number().nullable(),
  }),
  coauthors: z
    .object({
      _id: z.string().nullable(),
      slug: z.string().nullable(),
      displayName: z.string().nullable(),
      createdAt: z
        .union([z.string(), z.date()])
        .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
        .nullable(),
      profileImageId: z.string().nullable(),
      karma: z.number().nullable(),
      jobTitle: z.string().nullable(),
      organization: z.string().nullable(),
      postCount: z.number().nullable(),
      commentCount: z.number().nullable(),
    })
    .array(),
  tags: z
    .object({
      _id: z.string().nullable(),
      name: z.string().nullable(),
      slug: z.string().nullable(),
      core: z.boolean().nullable(),
    })
    .array(),
});

export type IFrontpagePostsList = z.infer<typeof frontpagePostsListSchema>;

export const frontpagePostsListParamsSchema = z.object({
  cutoffDays: z.int().nullable().optional(),
  scoreBias: z.number().nullable().optional(),
  timeDecayFactor: z.number().nullable().optional(),
  limit: z.int(),
});

export type IFrontpagePostsListParams = z.infer<
  typeof frontpagePostsListParamsSchema
>;

export const sidebarOpportunitiesSchema = z.object({
  _id: z.string(),
  slug: z.string(),
  title: z.string(),
  postedAt: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val)))),
  isEvent: z.boolean(),
  groupId: z.string().nullable(),
});

export type ISidebarOpportunities = z.infer<typeof sidebarOpportunitiesSchema>;

export const sidebarOpportunitiesParamsSchema = z.object({
  cutoffDays: z.int().nullable().optional(),
  scoreBias: z.number().nullable().optional(),
  timeDecayFactor: z.number().nullable().optional(),
  limit: z.int(),
});

export type ISidebarOpportunitiesParams = z.infer<
  typeof sidebarOpportunitiesParamsSchema
>;

export const sidebarEventsSchema = z.object({
  _id: z.string(),
  slug: z.string(),
  title: z.string(),
  startTime: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
    .nullable(),
  onlineEvent: z.boolean(),
  googleLocation: z.json().nullable(),
  isEvent: z.boolean(),
  groupId: z.string().nullable(),
});

export type ISidebarEvents = z.infer<typeof sidebarEventsSchema>;

export const sidebarEventsParamsSchema = z.object({
  limit: z.int(),
});

export type ISidebarEventsParams = z.infer<typeof sidebarEventsParamsSchema>;

export const postByIdSchema = z.object({
  _id: z.string(),
  title: z.string(),
  slug: z.string(),
  isEvent: z.boolean(),
  groupId: z.string().nullable(),
  eventImageId: z.string().nullable(),
  socialPreview: z.json().nullable(),
  socialPreviewImageAutoUrl: z.string().nullable(),
  readTimeMinutesOverride: z.number().nullable(),
  postedAt: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val)))),
  baseScore: z.number(),
  commentCount: z.number(),
  wordCount: z.number().nullable(),
  htmlHighlight: z.string().nullable(),
  user: z.object({
    _id: z.string().nullable(),
    slug: z.string().nullable(),
    displayName: z.string().nullable(),
    createdAt: z
      .union([z.string(), z.date()])
      .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
      .nullable(),
    profileImageId: z.string().nullable(),
    karma: z.number().nullable(),
    jobTitle: z.string().nullable(),
    organization: z.string().nullable(),
    postCount: z.number().nullable(),
    commentCount: z.number().nullable(),
  }),
  coauthors: z
    .object({
      _id: z.string().nullable(),
      slug: z.string().nullable(),
      displayName: z.string().nullable(),
      createdAt: z
        .union([z.string(), z.date()])
        .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
        .nullable(),
      profileImageId: z.string().nullable(),
      karma: z.number().nullable(),
      jobTitle: z.string().nullable(),
      organization: z.string().nullable(),
      postCount: z.number().nullable(),
      commentCount: z.number().nullable(),
    })
    .array(),
  tags: z
    .object({
      _id: z.string().nullable(),
      name: z.string().nullable(),
      slug: z.string().nullable(),
      core: z.boolean().nullable(),
    })
    .array(),
});

export type IPostById = z.infer<typeof postByIdSchema>;

export const postByIdParamsSchema = z.object({
  postId: z.string(),
  currentUserId: z.string().nullable().optional(),
  currentUserIsAdmin: z.boolean().nullable().optional(),
});

export type IPostByIdParams = z.infer<typeof postByIdParamsSchema>;

export const postBodyByIdSchema = z.object({
  _id: z.string(),
  body: z.string().nullable(),
});

export type IPostBodyById = z.infer<typeof postBodyByIdSchema>;

export const postBodyByIdParamsSchema = z.object({
  postId: z.string(),
  currentUserId: z.string().nullable().optional(),
  currentUserIsAdmin: z.boolean().nullable().optional(),
});

export type IPostBodyByIdParams = z.infer<typeof postBodyByIdParamsSchema>;
