import { expect, suite, test } from "vitest";
import { isNotRandomId, randomId } from "@/lib/utils/random";

suite("isNotRandomId", () => {
  test("returns false for valid random IDs generated by randomId", () => {
    const id = randomId();
    expect(isNotRandomId(id)).toBe(false);
  });
  test("returns true for strings that are not valid random IDs", () => {
    const invalidId = "invalid-id";
    expect(isNotRandomId(invalidId)).toBe(true);
  });
  test("returns true for strings of incorrect length", () => {
    const tooShortId = "short";
    const tooLongId = "thisiswaytoolongtobeavalidrandomid";
    expect(isNotRandomId(tooShortId)).toBe(true);
    expect(isNotRandomId(tooLongId)).toBe(true);
  });
  test("returns true for strings with invalid characters", () => {
    // Contains 'l', '0', and 'O' which are not in the unmistakableChars set
    const invalidCharsId = "ABCDEFG1l0O";
    expect(isNotRandomId(invalidCharsId, invalidCharsId.length)).toBe(true);
  });
});
