/* Generated by tradukisto - do not edit manually */

import type { Json, PostgresClient } from "tradukisto";

export interface IUserByAuth0Id {
  _id: string;
  banned: Date | null;
}

export interface IUserByAuth0IdParams {
  auth0Id: string;
}

export const userByAuth0IdSql = `-- Users.userByAuth0Id
SELECT "_id", "banned" FROM "Users" WHERE "services" -> 'auth0' ->> 'id' = $1::TEXT LIMIT 1`;

export interface ISaveUserLoginTokenParams {
  hashedToken: string;
  userId: string;
}

export const saveUserLoginTokenSql = `-- Users.saveUserLoginToken
UPDATE "Users" SET "services" = fm_add_to_set("services", '{resume,loginTokens}'::TEXT[], ('{"when":"' || NOW() || '","hashedToken":"' || $1::TEXT || '"}')::JSONB) WHERE "_id" = $2::TEXT`;

export interface ICurrentUser {
  _id: string;
  displayName: string | null;
  profileImageId: string | null;
  slug: string;
  isAdmin: boolean;
  theme: Json;
  hideIntercom: boolean;
  acceptedTos: boolean;
  hideNavigationSidebar: boolean | null;
  hideHomeRHS: boolean;
  currentFrontpageFilter: string | null;
  frontpageFilterSettings: Json | null;
  lastNotificationsCheck: Date | null;
  expandedFrontpageSections: Json | null;
}

export interface ICurrentUserParams {
  hashedToken: string;
}

export const currentUserSql = `-- Users.currentUser
SELECT "u"."_id", "u"."displayName", "u"."profileImageId", "u"."slug", "u"."isAdmin", "u"."theme", "u"."hideIntercom", "u"."acceptedTos", "u"."hideNavigationSidebar", "u"."hideHomeRHS", "u"."currentFrontpageFilter", "u"."frontpageFilterSettings", "u"."lastNotificationsCheck", "u"."expandedFrontpageSections" FROM "Users" AS "u" LEFT JOIN "UserLoginTokens" AS "lt" ON "lt"."userId" = "u"."_id" AND "lt"."hashedToken" = $1::TEXT WHERE "lt"."userId" IS NOT NULL OR "u"."services" -> 'resume' -> 'loginTokens' @> ('[{"hashedToken": "' || $1::TEXT || '"}]')::JSONB LIMIT 1`;

export class UsersRepo {
  protected client: PostgresClient;

  constructor(client: PostgresClient) {
    this.client = client;
  }

  async userByAuth0Id(params: IUserByAuth0IdParams): Promise<IUserByAuth0Id | null> {
    const res: IUserByAuth0Id[] = await this.client.fetchRows(userByAuth0IdSql, [
      params.auth0Id === undefined ? null : params.auth0Id,
    ]);
    return res?.[0] ?? null;
  }

  async saveUserLoginToken(params: ISaveUserLoginTokenParams): Promise<void> {
    await this.client.fetchRows(saveUserLoginTokenSql, [
      params.hashedToken === undefined ? null : params.hashedToken,
      params.userId === undefined ? null : params.userId,
    ]);
  }

  async currentUser(params: ICurrentUserParams): Promise<ICurrentUser | null> {
    const res: ICurrentUser[] = await this.client.fetchRows(currentUserSql, [
      params.hashedToken === undefined ? null : params.hashedToken,
    ]);
    return res?.[0] ?? null;
  }
}
