/* Generated by tradukisto - do not edit manually */

import z from "zod/v4";

export const userByAuth0IdSchema = z.object({
  _id: z.string(),
  banned: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
    .nullable(),
});

export type IUserByAuth0Id = z.infer<typeof userByAuth0IdSchema>;

export const userByAuth0IdParamsSchema = z.object({
  auth0Id: z.string(),
});

export type IUserByAuth0IdParams = z.infer<typeof userByAuth0IdParamsSchema>;

export const saveUserLoginTokenParamsSchema = z.object({
  hashedToken: z.string(),
  userId: z.string(),
});

export type ISaveUserLoginTokenParams = z.infer<
  typeof saveUserLoginTokenParamsSchema
>;

export const currentUserSchema = z.object({
  _id: z.string(),
  displayName: z.string().nullable(),
  profileImageId: z.string().nullable(),
  slug: z.string(),
  isAdmin: z.boolean(),
  theme: z.json(),
  hideIntercom: z.boolean(),
  acceptedTos: z.boolean(),
  hideNavigationSidebar: z.boolean().nullable(),
  hideHomeRHS: z.boolean(),
  currentFrontpageFilter: z.string().nullable(),
  frontpageFilterSettings: z.json().nullable(),
  lastNotificationsCheck: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
    .nullable(),
  expandedFrontpageSections: z.json().nullable(),
});

export type ICurrentUser = z.infer<typeof currentUserSchema>;

export const currentUserParamsSchema = z.object({
  hashedToken: z.string(),
});

export type ICurrentUserParams = z.infer<typeof currentUserParamsSchema>;
