/* Generated by tradukisto - do not edit manually */

import type { PostgresClient } from "tradukisto";

export interface IUserByAuth0Id {
  _id: string;
  username: string | null;
  emails: any[] | null;
  isAdmin: boolean;
  profile: any | null;
  services: any | null;
  displayName: string | null;
  previousDisplayName: string | null;
  email: string | null;
  slug: string;
  noindex: boolean;
  groups: string[] | null;
  lwWikiImport: boolean | null;
  theme: any;
  lastUsedTimezone: string | null;
  whenConfirmationEmailSent: Date | null;
  legacy: boolean;
  commentSorting: string | null;
  sortDraftsBy: string | null;
  noKibitz: boolean | null;
  showHideKarmaOption: boolean | null;
  showPostAuthorCard: boolean | null;
  hideIntercom: boolean;
  markDownPostEditor: boolean;
  hideElicitPredictions: boolean;
  hideAFNonMemberInitialWarning: boolean;
  noSingleLineComments: boolean;
  noCollapseCommentsPosts: boolean;
  noCollapseCommentsFrontpage: boolean;
  showCommunityInRecentDiscussion: boolean;
  petrovOptOut: boolean;
  acceptedTos: boolean;
  hideNavigationSidebar: boolean | null;
  currentFrontpageFilter: string | null;
  frontpageFilterSettings: any | null;
  hideFrontpageFilterSettingsDesktop: boolean | null;
  allPostsTimeframe: string | null;
  allPostsFilter: string | null;
  allPostsSorting: string | null;
  allPostsShowLowKarma: boolean | null;
  allPostsIncludeEvents: boolean | null;
  allPostsOpenSettings: boolean | null;
  draftsListSorting: string | null;
  draftsListShowArchived: boolean | null;
  draftsListShowShared: boolean | null;
  lastNotificationsCheck: Date | null;
  karma: number;
  goodHeartTokens: number | null;
  moderationStyle: string | null;
  moderatorAssistance: boolean | null;
  collapseModerationGuidelines: boolean | null;
  bannedUserIds: string[] | null;
  bannedPersonalUserIds: string[] | null;
  hiddenPostsMetadata: any[];
  legacyId: string | null;
  deleted: boolean;
  voteBanned: boolean | null;
  nullifyVotes: boolean | null;
  deleteContent: boolean | null;
  banned: Date | null;
  auto_subscribe_to_my_posts: boolean;
  auto_subscribe_to_my_comments: boolean;
  autoSubscribeAsOrganizer: boolean;
  notificationCommentsOnSubscribedPost: any;
  notificationShortformContent: any;
  notificationRepliesToMyComments: any;
  notificationRepliesToSubscribedComments: any;
  notificationSubscribedUserPost: any;
  notificationPostsInGroups: any;
  notificationSubscribedTagPost: any;
  notificationPrivateMessage: any;
  notificationSharedWithMe: any;
  notificationAlignmentSubmissionApproved: any;
  notificationEventInRadius: any;
  notificationRSVPs: any;
  notificationGroupAdministration: any;
  notificationCommentsOnDraft: any;
  notificationPostsNominatedReview: any;
  notificationSubforumUnread: any;
  notificationNewMention: any;
  karmaChangeNotifierSettings: any;
  karmaChangeLastOpened: Date | null;
  karmaChangeBatchStart: Date | null;
  emailSubscribedToCurated: boolean | null;
  subscribedToDigest: boolean;
  unsubscribeFromAll: boolean | null;
  hideSubscribePoke: boolean;
  hideMeetupsPoke: boolean;
  frontpagePostCount: number;
  sequenceCount: number;
  sequenceDraftCount: number;
  mongoLocation: any | null;
  googleLocation: any | null;
  location: string | null;
  mapLocation: any | null;
  mapLocationSet: boolean | null;
  mapMarkerText: string | null;
  htmlMapMarkerText: string | null;
  nearbyEventsNotifications: boolean;
  nearbyEventsNotificationsLocation: any | null;
  nearbyEventsNotificationsMongoLocation: any | null;
  nearbyEventsNotificationsRadius: number | null;
  nearbyPeopleNotificationThreshold: number | null;
  hideFrontpageMap: boolean | null;
  hideTaggingProgressBar: boolean | null;
  hideFrontpageBookAd: boolean | null;
  hideFrontpageBook2019Ad: boolean | null;
  sunshineNotes: string;
  sunshineFlagged: boolean;
  needsReview: boolean;
  sunshineSnoozed: boolean;
  snoozedUntilContentCount: number | null;
  reviewedByUserId: string | null;
  reviewedAt: Date | null;
  afKarma: number;
  voteCount: number | null;
  smallUpvoteCount: number | null;
  smallDownvoteCount: number | null;
  bigUpvoteCount: number | null;
  bigDownvoteCount: number | null;
  usersContactedBeforeReview: string[] | null;
  fullName: string | null;
  shortformFeedId: string | null;
  viewUnreviewedComments: boolean | null;
  partiallyReadSequences: any[] | null;
  beta: boolean | null;
  reviewVotesQuadratic: boolean | null;
  reviewVotesQuadratic2019: boolean | null;
  reviewVotesQuadratic2020: boolean | null;
  petrovPressedButtonDate: Date | null;
  petrovLaunchCodeDate: Date | null;
  defaultToCKEditor: boolean | null;
  signUpReCaptchaRating: number | null;
  oldSlugs: string[];
  noExpandUnreadCommentsReview: boolean;
  postCount: number;
  maxPostCount: number;
  commentCount: number;
  maxCommentCount: number;
  tagRevisionCount: number;
  abTestKey: string;
  abTestOverrides: any | null;
  walledGardenInvite: boolean | null;
  hideWalledGardenUI: boolean | null;
  walledGardenPortalOnboarded: boolean | null;
  taggingDashboardCollapsed: boolean | null;
  usernameUnset: boolean;
  paymentEmail: string | null;
  paymentInfo: string | null;
  profileImageId: string | null;
  jobTitle: string | null;
  organization: string | null;
  careerStage: string[] | null;
  website: string | null;
  fmCrosspostUserId: string | null;
  linkedinProfileURL: string | null;
  facebookProfileURL: string | null;
  twitterProfileURL: string | null;
  githubProfileURL: string | null;
  profileTagIds: string[];
  organizerOfGroupIds: string[];
  programParticipation: string[] | null;
  postingDisabled: boolean | null;
  allCommentingDisabled: boolean | null;
  commentingOnOtherUsersDisabled: boolean | null;
  conversationsDisabled: boolean | null;
  acknowledgedNewUserGuidelines: boolean | null;
  subforumPreferredLayout: string | null;
  allowDatadogSessionReplay: boolean;
  afPostCount: number;
  afCommentCount: number;
  afSequenceCount: number;
  afSequenceDraftCount: number;
  reviewForAlignmentForumUserId: string | null;
  afApplicationText: string | null;
  afSubmittedApplication: boolean | null;
  schemaVersion: number | null;
  createdAt: Date | null;
  legacyData: any | null;
  moderationGuidelines: any | null;
  moderationGuidelines_latest: string | null;
  howOthersCanHelpMe: any | null;
  howOthersCanHelpMe_latest: string | null;
  howICanHelpOthers: any | null;
  howICanHelpOthers_latest: string | null;
  biography: any | null;
  biography_latest: string | null;
  recommendationSettings: any | null;
  allPostsHideCommunity: boolean | null;
  notificationDebateCommentsOnSubscribedPost: any;
  notificationDebateReplies: any;
  hideCommunitySection: boolean;
  expandedFrontpageSections: any | null;
  voteReceivedCount: number | null;
  smallUpvoteReceivedCount: number | null;
  smallDownvoteReceivedCount: number | null;
  bigUpvoteReceivedCount: number | null;
  bigDownvoteReceivedCount: number | null;
  hidePostsRecommendations: boolean;
  reactPaletteStyle: string;
  hideHomeRHS: boolean;
  hideFrontpageBook2020Ad: boolean | null;
  notificationDialogueMessages: any;
  notificationPublishedDialogueMessages: any;
  hideDialogueFacilitation: boolean;
  notificationAddedAsCoauthor: any;
  optedInToDialogueFacilitation: boolean;
  revealChecksToAdmins: boolean;
  notificationDialogueMatch: any;
  notificationKarmaPowersGained: any;
  showDialoguesList: boolean;
  showMyDialogues: boolean;
  showMatches: boolean;
  showRecommendedPartners: boolean;
  notificationNewDialogueChecks: any;
  hideActiveDialogueUsers: boolean;
  notificationYourTurnMatchForm: any;
  hideSunshineSidebar: boolean;
  hideJobAdUntil: Date | null;
  linkedGoogleRefreshToken: string | null;
  notificationSubscribedUserComment: any;
  attemptedToContactBeforeReview: string[] | null;
  inactiveSurveyEmailSentAt: Date | null;
  notificationSubscribedSequencePost: any;
  hideFromPeopleDirectory: boolean;
  profileUpdatedAt: Date;
  frontpageSelectedTab: string | null;
  optedOutOfSurveys: boolean | null;
  permanentDeletionRequestedAt: Date | null;
  userSurveyEmailSentAt: Date | null;
  criticismTipsDismissed: boolean;
  postGlossariesPinned: boolean;
  generateJargonForDrafts: boolean;
  generateJargonForPublishedPosts: boolean;
  twitterProfileURLAdmin: string | null;
  blueskyProfileURL: string | null;
  subscribedToNewsletter: boolean;
  keywordAlerts: string[];
  notificationKeywordAlert: any;
  notificationNewPingback: any;
  bookmarksCount: number;
  mentionsDisabled: boolean;
  sendInactiveSummaryEmail: boolean;
  inactiveSummaryEmailSentAt: Date | null;
}

export interface IUserByAuth0IdParams {
  auth0Id?: string | null;
}

export const userByAuth0IdSql = `-- Users.userByAuth0Id
SELECT * FROM "Users" WHERE "services" -> 'auth0' ->> 'id' = $1::TEXT LIMIT 1`;

export class UsersRepo {
  protected client: PostgresClient;

  constructor(client: PostgresClient) {
    this.client = client;
  }

  userByAuth0Id(params: IUserByAuth0IdParams): Promise<IUserByAuth0Id[]> {
    return this.client.fetchRows(userByAuth0IdSql, [
      params.auth0Id === undefined ? null : params.auth0Id,
    ]);
  }

  async saveUserLoginToken({
    userId,
    hashedToken,
  }: {
    userId: string;
    hashedToken: string;
  }): Promise<void> {
    await this.client.fetchRows(
      `
UPDATE "Users"
SET "services" = fm_add_to_set(
  "services",
  '{resume,loginToken}'::TEXT[],
  ('{"when":"' || NOW() || '","hashedToken":"' || $2 || '"}')::JSONB
)
WHERE "_id" = $1
    `,
      [userId, hashedToken],
    );
  }
}
