/* Generated by tradukisto - do not edit manually */

import z from "zod/v4";

export const notificationDisplaysSchema = z.object({
  _id: z.string(),
  type: z.string(),
  link: z.string().nullable(),
  viewed: z.boolean(),
  message: z.string(),
  createdAt: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
    .nullable(),
  extraData: z.json().nullable(),
  tagRelId: z.string().nullable(),
  post: z
    .object({
      _id: z.string().nullable(),
      slug: z.string().nullable(),
      title: z.string().nullable(),
      draft: z.boolean().nullable(),
      url: z.string().nullable(),
      isEvent: z.boolean().nullable(),
      startTime: z
        .union([z.string(), z.date()])
        .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
        .nullable(),
      curatedDate: z
        .union([z.string(), z.date()])
        .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
        .nullable(),
      postedAt: z
        .union([z.string(), z.date()])
        .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
        .nullable(),
      groupId: z.string().nullable(),
      fmCrosspost: z.json().nullable(),
      collabEditorDialogue: z.boolean().nullable(),
      readTimeMinutesOverride: z.number().nullable(),
      wordCount: z.number().nullable(),
      socialPreviewData: z.object({
        imageUrl: z.string().nullable(),
      }),
      customHighlight: z.json().nullable(),
      contents: z
        .object({
          html: z.string().nullable(),
          wordCount: z.number().nullable(),
          originalContents: z.json().nullable(),
          editedAt: z
            .union([z.string(), z.date()])
            .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
            .nullable(),
          userId: z.string().nullable(),
          version: z.string().nullable(),
        })
        .nullable(),
      rsvps: z.json().array().nullable(),
      user: z
        .object({
          _id: z.string().nullable(),
          slug: z.string().nullable(),
          createdAt: z
            .union([z.string(), z.date()])
            .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
            .nullable(),
          displayName: z.string().nullable(),
          profileImageId: z.string().nullable(),
          karma: z.number().nullable(),
          deleted: z.boolean().nullable(),
          htmlBio: z.string(),
          postCount: z.number().nullable(),
          commentCount: z.number().nullable(),
        })
        .nullable(),
      group: z
        .object({
          _id: z.string().nullable(),
          name: z.string().nullable(),
        })
        .nullable(),
    })
    .nullable(),
  comment: z
    .object({
      _id: z.string().nullable(),
      user: z
        .object({
          _id: z.string().nullable(),
          slug: z.string().nullable(),
          createdAt: z
            .union([z.string(), z.date()])
            .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
            .nullable(),
          displayName: z.string().nullable(),
          profileImageId: z.string().nullable(),
          karma: z.number().nullable(),
          deleted: z.boolean().nullable(),
          htmlBio: z.string(),
          postCount: z.number().nullable(),
          commentCount: z.number().nullable(),
        })
        .nullable(),
      post: z
        .object({
          _id: z.string().nullable(),
          slug: z.string().nullable(),
          title: z.string().nullable(),
          draft: z.boolean().nullable(),
          url: z.string().nullable(),
          isEvent: z.boolean().nullable(),
          startTime: z
            .union([z.string(), z.date()])
            .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
            .nullable(),
          curatedDate: z
            .union([z.string(), z.date()])
            .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
            .nullable(),
          postedAt: z
            .union([z.string(), z.date()])
            .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
            .nullable(),
          groupId: z.string().nullable(),
          fmCrosspost: z.json().nullable(),
          collabEditorDialogue: z.boolean().nullable(),
          readTimeMinutesOverride: z.number().nullable(),
          wordCount: z.number().nullable(),
          socialPreviewData: z.object({
            imageUrl: z.string().nullable(),
          }),
          customHighlight: z.json().nullable(),
          contents: z
            .object({
              html: z.string().nullable(),
              wordCount: z.number().nullable(),
              originalContents: z.json().nullable(),
              editedAt: z
                .union([z.string(), z.date()])
                .pipe(
                  z.transform((val) => (val instanceof Date ? val : new Date(val))),
                )
                .nullable(),
              userId: z.string().nullable(),
              version: z.string().nullable(),
            })
            .nullable(),
          rsvps: z.json().array().nullable(),
          user: z
            .object({
              _id: z.string().nullable(),
              slug: z.string().nullable(),
              createdAt: z
                .union([z.string(), z.date()])
                .pipe(
                  z.transform((val) => (val instanceof Date ? val : new Date(val))),
                )
                .nullable(),
              displayName: z.string().nullable(),
              profileImageId: z.string().nullable(),
              karma: z.number().nullable(),
              deleted: z.boolean().nullable(),
              htmlBio: z.string(),
              postCount: z.number().nullable(),
              commentCount: z.number().nullable(),
            })
            .nullable(),
          group: z
            .object({
              _id: z.string().nullable(),
              name: z.string().nullable(),
            })
            .nullable(),
        })
        .nullable(),
    })
    .nullable(),
  tag: z
    .object({
      _id: z.string().nullable(),
      name: z.string().nullable(),
      slug: z.string().nullable(),
    })
    .nullable(),
  sequence: z
    .object({
      _id: z.string().nullable(),
      title: z.string().nullable(),
    })
    .nullable(),
  user: z
    .object({
      _id: z.string().nullable(),
      slug: z.string().nullable(),
      createdAt: z
        .union([z.string(), z.date()])
        .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
        .nullable(),
      displayName: z.string().nullable(),
      profileImageId: z.string().nullable(),
      karma: z.number().nullable(),
      deleted: z.boolean().nullable(),
      htmlBio: z.string(),
      postCount: z.number().nullable(),
      commentCount: z.number().nullable(),
    })
    .nullable(),
  localgroup: z
    .object({
      _id: z.string().nullable(),
      name: z.string().nullable(),
    })
    .nullable(),
});

export type INotificationDisplays = z.infer<typeof notificationDisplaysSchema>;

export const notificationDisplaysParamsSchema = z.object({
  postSocialPreviewPrefix: z.string(),
  userId: z.string(),
  type: z.string().nullable().optional(),
  limit: z.int(),
  offset: z.int(),
});

export type INotificationDisplaysParams = z.infer<
  typeof notificationDisplaysParamsSchema
>;
