/* Generated by tradukisto - do not edit manually */

import type { PostgresClient } from "tradukisto";

export interface IFrontpageQuickTakes {
  _id: string;
  baseScore: number;
  voteCount: number;
  postedAt: Date;
  descendentCount: number;
  html: string | null;
  user: {
    _id: string;
    slug: string;
    displayName: string;
    createdAt: Date | null;
    profileImageId: string | null;
    karma: number;
    jobTitle: string | null;
    organization: string | null;
    postCount: number;
    commentCount: number;
  };
}

export interface IFrontpageQuickTakesParams {
  cutoffDays?: number | null;
  limit: number;
}

export const frontpageQuickTakesSql = `-- Comments.frontpageQuickTakes
SELECT "c"."_id", "c"."baseScore", "c"."voteCount", "c"."postedAt", "c"."descendentCount", "contents"."html", JSON_BUILD_OBJECT('_id', "u"."_id", 'slug', "u"."slug", 'displayName', "u"."displayName", 'createdAt', "u"."createdAt", 'profileImageId', "u"."profileImageId", 'karma', "u"."karma", 'jobTitle', "u"."jobTitle", 'organization', "u"."organization", 'postCount', "u"."postCount", 'commentCount', "u"."commentCount") AS "user" FROM "Comments" AS "c" INNER JOIN "Users" AS "u" ON "c"."userId" = "u"."_id" AND NOT "u"."deleted" INNER JOIN "Revisions" AS "contents" ON "c"."contents_latest" = "contents"."_id" WHERE NOT "c"."rejected" AND NOT COALESCE("c"."debateResponse", FALSE) AND NOT "c"."authorIsUnreviewed" AND "c"."shortform" AND "c"."shortformFrontpage" AND NOT "c"."deleted" AND "c"."parentCommentId" IS NULL AND "c"."createdAt" > NOW() - MAKE_INTERVAL(days => COALESCE($1::INTEGER, 5)) AND (("c"."baseScore" >= 1 AND "c"."createdAt" < NOW() - MAKE_INTERVAL(hours => 2)) OR ("c"."baseScore" >= -5 AND "c"."createdAt" >= NOW() - MAKE_INTERVAL(hours => 2))) ORDER BY "c"."score" DESC, "c"."lastSubthreadActivity" DESC, "c"."postedAt" DESC LIMIT $2`;

export class CommentsRepo {
  protected client: PostgresClient;

  constructor(client: PostgresClient) {
    this.client = client;
  }

  frontpageQuickTakes(
    params: IFrontpageQuickTakesParams,
  ): Promise<IFrontpageQuickTakes[]> {
    return this.client.fetchRows(frontpageQuickTakesSql, [
      params.cutoffDays === undefined ? null : params.cutoffDays,
      params.limit === undefined ? null : params.limit,
    ]);
  }
}
