/* Generated by tradukisto - do not edit manually */

import z from "zod/v4";

export const frontpageQuickTakesSchema = z.object({
  _id: z.string(),
  baseScore: z.number(),
  voteCount: z.number(),
  postedAt: z
    .union([z.string(), z.date()])
    .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val)))),
  descendentCount: z.number(),
  html: z.string().nullable(),
  user: z.object({
    _id: z.string(),
    slug: z.string(),
    displayName: z.string(),
    createdAt: z
      .union([z.string(), z.date()])
      .pipe(z.transform((val) => (val instanceof Date ? val : new Date(val))))
      .nullable(),
    profileImageId: z.string().nullable(),
    karma: z.number(),
    jobTitle: z.string().nullable(),
    organization: z.string().nullable(),
    postCount: z.number(),
    commentCount: z.number(),
  }),
});

export type IFrontpageQuickTakes = z.infer<typeof frontpageQuickTakesSchema>;

export const frontpageQuickTakesParamsSchema = z.object({
  cutoffDays: z.int().nullable().optional(),
  limit: z.int(),
});

export type IFrontpageQuickTakesParams = z.infer<
  typeof frontpageQuickTakesParamsSchema
>;
